import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import "./globals.css";

const spaceMono = Space_Mono({ weight: "700", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Frontend Mentor | Tip calculator app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="./images/favicon-32x32.png"
      ></link>
      <body className={spaceMono.className}>{children}</body>
    </html>
  );
}
